### ISSUE TITLE
Get an error when running roslaunch

### ISSUE THREAD

**Issue by xingtong1997** [KTH-SML/svea#21]
Hi,

I connected my laptop to svea4, built a docker container, entered the container and run the command 'roslaunch svea_core state_publisher.launch', then I got this [error](https://drive.google.com/file/d/1smRvvfVa96UNNLlVqCEQHSDwCyOtybT9/view?usp=drive_link)

**Comment by kaarmu** [comment]
The problem is this line, https://github.com/KTH-SML/svea/blob/f10824de76d15f88cda880202fb8fd71bbca36b3/src/svea_core/scripts/state_publisher.py#L31.

It should say `self.SPIN_RATE`.
