### ISSUE TITLE
Pure Pursuit Controller Parameters Assignment

### ISSUE THREAD

**Issue by Fedezac** [KTH-SML/svea#8]
In the [pure_pursuit.py](https://github.com/KTH-SML/svea/blob/main/src/svea_examples/scripts/pure_pursuit.py) node of the `svea_example` package, a PurePursuitController gets passed to the SVEAPurePursuit object. In the global scope of [path_following_svea.py](https://github.com/KTH-SML/svea/blob/main/src/svea_core/src/svea/svea_managers/path_following_sveas.py), where the SVEAPurePursuit class is defined, three parameters of the PurePursuitController are assigned: in this way three variables valid at a module level are instatiated, without actually modifying the relative class attributes (which are used for the actual control).
A possible fix could be removing this three lines of code from the [path_following_svea.py](https://github.com/KTH-SML/svea/blob/main/src/svea_core/src/svea/svea_managers/path_following_sveas.py) component:
```python
pure_pursuit.k = 0.6  # look forward gain
pure_pursuit.Lfc = 0.4  # look-ahead distance
pure_pursuit.L = 0.324  # [m] wheel base of vehicle
```

**Comment by kaarmu** [comment]
Great this is also solved now with #10.

The actual parameters to tune the controller can be found at pure_pursuit.py#L9
